### ISSUE TITLE
running python sample test in mac

### ISSUE THREAD

**Issue by pratimash** [appium/appium-safari-driver#13]
Hi,
 i am trying to run # Python3 + PyTest given the README.md.

When I run its not running, tests.
============================================== test session starts 
platform darwin -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
collected 0 items                                                                                                
======================================== no tests ran in 60.58s (0:01:00) 

Can you please help me to run the tests.

**Comment by KazuCocoa** [comment]
How did you start the example? Probably pytest can find tests like: `pytest example.py`
