### ISSUE TITLE
driver.delete_cookie and driver.delete_all_cookies() doesn't work

### ISSUE THREAD

**Issue by DuXspace** [appium/appium-safari-driver#22]
Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 400

`from appium import webdriver

desired_caps = {
    "automationName": "Safari",
    "platformName": "iOS",
    'safari:deviceName': "iPhone 12 mini",
    "platformVersion": "15.2",
    "browserName": "Safari",
    "autoWebview": "true",
    'safari:useSimulator': True,
}

driver = webdriver.Remote('0.0.0.0:4723/wd/hub', desired_caps)
driver.get("http://google.com")
driver.delete_all_cookies()
driver.quit()`

Appium version: 1.23.0-beta.0
Appium logs:
https://gist.github.com/DuXspace/accddb3fe89828a62f02d2527e118922

**Comment by mykola-mokhnach** [comment]
Unfortunately this is beyond Appium's control. Only Apple controls the list of endpoints that their server provides

**Comment by DuXspace** [comment]
@mykola-mokhnach hm, thats weird, because i see in logs:
Proxying [DELETE /wd/hub/session/5952327a-fad4-4eac-a461-70f3c4bdd6f1/cookie] to [DELETE http://127.0.0.1:5100/session/E8F74479-636B-4237-AEEA-7E47375C2BF6/cookie] with body: {}

when im sending by postman this req "/wd/hub/session/5952327a-fad4-4eac-a461-70f3c4bdd6f1/cookie" I'm receiving an error "Original error: Could not proxy. Proxy error: Request failed with status code 400"
But when i send http://127.0.0.1:5100/session/E8F74479-636B-4237-AEEA-7E47375C2BF6/cookie by postman, it works, and cookies are cleared, but i can't understand how can i get session_id like "E8F74479-636B-4237-AEEA-7E47375C2BF6"

Also this problem can' be solved like this, but i think its better to use default methods everywhere:

`js = 'function deleteAllCookies() {' \
    'var cookies = document.cookie.split(";");' \
    'for (var i = 0; i < cookies.length; i++) {' \
        'var cookie = cookies[i];'\
        'var eqPos = cookie.indexOf("=");'\
        'var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;'\
        'document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";'\
    '}'\
'}'\
'deleteAllCookies();'

driver.execute_script(js)
driver.refresh()`

**Comment by mykola-mokhnach** [comment]
If you say that it worked using POSTMAN then it might be that Safaridriver does not like the fact that not an empty body is sent by DELETE request. https://github.com/appium/appium-safari-driver/pull/23 should address that

**Comment by DuXspace** [comment]
yeah, you're right, i send by postman with empty body and received a 400 error. Thank you! Waiting for merge

**Comment by mykola-mokhnach** [comment]
I have published the patch. You could only try it in Appium2 though

**Comment by DuXspace** [comment]
@mykola-mokhnach hey, looks like it works properly, will you integrate it in stable appium?
