### ISSUE TITLE
Request failed with status 405 due to Method is not implemented-while switching to parent frame

### ISSUE THREAD

**Issue by EINBOX** [appium/appium-safari-driver#26]
i am facing an issue on ios safari browser while switching frame to parent frame
code : driver. switchToParentFrame()
**```
error:
request failed due to response error: unknown method
WARN webdriver: Request failed with status 405 due to Method is not implemented
```**
device info: ios 14.4 ,iphone 12 pro simulator
browser :safari
can some one help to get it fix or any alternative solution for this?

**Comment by jlipps** [comment]
please include your complete appium logs
