### ISSUE TITLE
[WebRTC]When Safari is in remote automation, it can only use mock capture devices

### ISSUE THREAD

**Issue by Teiyui** [appium/appium-safari-driver#27]
Nice to meet you. I'm remotely controlling the Safari to start a Webex meeting which is based on WebRTC, but when I press the Audio and Video settings buttons, it can only shows the Mock device rather than real device, the images below show what I have met:

<img width="1580" alt="Screen Shot 2022-03-15 at 2 58 33 PM" src="https://user-images.githubusercontent.com/61471911/158323522-d513efc0-c2b2-4a41-b53d-21d2152c12bd.png">

<img width="1573" alt="Screen Shot 2022-03-15 at 3 00 18 PM" src="https://user-images.githubusercontent.com/61471911/158323735-2c85650c-3760-41f3-8856-9a081743baf8.png">

And if I use [WebRTC](https://webrtc.github.io/samples/src/content/devices/input-output/) samples to select Audio&Video device, it also can only show Mock devices:

<img width="1579" alt="Screen Shot 2022-03-15 at 3 04 18 PM" src="https://user-images.githubusercontent.com/61471911/158324234-efe26ade-7570-4f32-a7fb-eb0e6947698b.png">

But when I use Safari which isn't in remote automation, it can use another capture devices:

<img width="1577" alt="Screen Shot 2022-03-15 at 3 09 50 PM" src="https://user-images.githubusercontent.com/61471911/158324993-f00bd581-977c-4246-b9b6-00babb365107.png">

I'm wondering whether there is a parameter could cancel mock capture devices in remote automated Safari, If not, would you like to give me a suggestion on which organization I could ask for help.

**Comment by mykola-mokhnach** [comment]
I assume you could try to play with [webkit:WebRTC](https://github.com/appium/appium-safari-driver#usage) capability values. The driver itself is developed by Apple, Appium acts as a simple proxy there, so there's not much we could do from our side.

**Comment by Teiyui** [comment]
Thank you, I will ask Apple Developer for help.
